[project]
name = "pipeline-peril-pygame"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "numpy>=2.3.3",
    "pygame>=2.6.1",
    "pytest>=8.4.2",
    "requests>=2.32.5",
]
